version: '3'

services:
# -----------------------
  backend:
    build:
      context: ./backend
    ports:
      - 3000:3000
    depends_on:
      - mongo
# -----------------------
  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    depends_on:
      - backend
      - ml_backend
# ----------------------
  ml_backend:
    build:
      context: ./ml_backend
    ports:
      - 8000:8000
    depends_on:
      - postgres
# -----------------------
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
# -----------------------
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myapp
    ports:
      - 5432:5432
# -----------------------